#ifndef _AM_ERRORS_H
#define _AM_ERRORS_H

#include <3ds/result.h>

// module specific am

#define AM_GENERAL_IO_FAILURE                MAKERESULT(RL_STATUS   , RS_INVALIDARG  , RM_AM,   1) // C8E08001
#define AM_INVALIDATED_INSTALLATTION_STATE   MAKERESULT(RL_PERMANENT, RS_INVALIDSTATE, RM_AM,   2) // D8A08002
#define AM_INVALID_CONTENT_IMPORT_STATE      MAKERESULT(RL_PERMANENT, RS_INVALIDSTATE, RM_AM,   4) // D8A08004
#define AM_PIPE_UNSUPPORTED_ACTION           MAKERESULT(RL_PERMANENT, RS_NOTSUPPORTED, RM_AM,   8) // D8C08008
#define AM_PIPE_ALREADY_INITIALIZED          MAKERESULT(RL_PERMANENT, RS_INVALIDSTATE, RM_AM,   9) // D8A08009
#define AM_META_REGION_NOT_FOUND             MAKERESULT(RL_PERMANENT, RS_NOTFOUND    , RM_AM,  19) // D8808013
#define AM_TRYING_TO_INSTALL_OUTDATED_TICKET MAKERESULT(RL_PERMANENT, RS_INVALIDARG  , RM_AM,  25) // D8E08019
#define AM_GENERAL_INVALIDARG                MAKERESULT(RL_USAGE    , RS_INVALIDARG  , RM_AM,  31) // E0E0801F
#define AM_TWL_EXPORT_INVALID_ENUM_VALUE     MAKERESULT(RL_USAGE    , RS_NOTSUPPORTED, RM_AM,  40) // E0C08028
#define AM_GENERAL_INTERNAL_ERROR            MAKERESULT(RL_PERMANENT, RS_INVALIDSTATE, RM_AM,  41) // D8E08029 (Default Internal Result?)
#define AM_TRYING_TO_UNINSTALL_SYSAPP        MAKERESULT(RL_USAGE    , RS_INVALIDARG  , RM_AM,  44) // C8A0802C
#define AM_MOVABLE_VERIFY_SUCCESS            MAKERESULT(RL_STATUS   , RS_INVALIDSTATE, RM_AM,  46) // C8A0802E
#define AM_FOOTER_SECTION_HASH_MISMATCH      MAKERESULT(RL_STATUS   , RS_INVALIDSTATE, RM_AM,  48) // C8A08030
#define AM_SECTION_CMAC_VERIFY_FAIL          MAKERESULT(RL_STATUS   , RS_INVALIDSTATE, RM_AM,  49) // C8A08031
#define AM_FAILED_READING_BLOCKMETA          MAKERESULT(RL_STATUS   , RS_INVALIDSTATE, RM_AM,  51) // C8A08033
#define AM_INVALID_EXPORT                    MAKERESULT(RL_STATUS   , RS_INVALIDSTATE, RM_AM,  52) // C8A08034
#define AM_INVALID_TITLE_ID_HIGH             MAKERESULT(RL_USAGE    , RS_INVALIDARG  , RM_AM,  60) // E0E0803C
#define AM_CIA_META_READ_SIZE_TOO_SMALL      MAKERESULT(RL_PERMANENT, RS_WRONGARG    , RM_AM,  63) // D900803F
#define AM_TICKET_UNEXPECTED_TITLE_ID        MAKERESULT(RL_PERMANENT, RS_INVALIDSTATE, RM_AM,  68) // D8A08044
#define AM_TMD_UNEXPECTED_TITLE_ID           MAKERESULT(RL_PERMANENT, RS_INVALIDSTATE, RM_AM,  69) // D8A08045

/* these are shared (also used in AM9) */

#define AM_INVALID_CONTENT_INDEX_SIZE        MAKERESULT(RL_PERMANENT, RS_INVALIDARG  , RM_AM, 101) // D8E08065 (Internal Result  -1)
#define AM_GENERAL_INTERNAL_INVALIDARG       MAKERESULT(RL_PERMANENT, RS_INVALIDARG  , RM_AM, 102) // D8E08066 (Internal Result  -2)
#define AM_PREVIOUS_RESULT_FAILED            MAKERESULT(RL_PERMANENT, RS_INVALIDARG  , RM_AM, 103) // D8E08067 (Internal Result  -3)
#define AM_IO_SIZE_MISMATCH                  MAKERESULT(RL_PERMANENT, RS_INVALIDARG  , RM_AM, 104) // D8E08068 (Internal Result  -4)
#define AM_CERT_SIG_HASH_CHECK_FAILED        MAKERESULT(RL_PERMANENT, RS_INVALIDARG  , RM_AM, 106) // D8E0806A (Internal Result  -6)
#define AM_INVALID_SIGNATURE_TYPE            MAKERESULT(RL_PERMANENT, RS_INVALIDARG  , RM_AM, 109) // D8E0806D (Internal Result  -9)
#define AM_INVALID_TICKET_VERSION            MAKERESULT(RL_PERMANENT, RS_INVALIDARG  , RM_AM, 111) // D8E0806F (Internal Result -11)

#define AM_INTERNAL_RESULT(x) (AM_INVALID_CONTENT_INDEX_SIZE - (x + 1))

/*
    no idea what these are, not used in AM11
    they can probably be named if i take the time to look in AM9

    -5      -> 0xD8E08069 MAKERESULT(RL_PERMANENT, RS_INVALIDARG  , RM_AM, 105) Unknown
    -7      -> 0xD8E0806B MAKERESULT(RL_PERMANENT, RS_INVALIDARG  , RM_AM, 107) Unknown
    -8      -> 0xD8E0806C MAKERESULT(RL_PERMANENT, RS_INVALIDARG  , RM_AM, 108) Unknown
    -10     -> 0xD8E0806E MAKERESULT(RL_PERMANENT, RS_INVALIDARG  , RM_AM, 110) Unknown
    -12     -> 0xD8E08070 MAKERESULT(RL_PERMANENT, RS_INVALIDARG  , RM_AM, 112) Unknown
    -13     -> 0xD8E08071 MAKERESULT(RL_PERMANENT, RS_INVALIDARG  , RM_AM, 113) Unknown
    -14     -> 0xD8E08072 MAKERESULT(RL_PERMANENT, RS_INVALIDARG  , RM_AM, 114) Unknown
*/

// module specific os

#define OS_REMOTE_SESSION_CLOSED         MAKERESULT(RL_STATUS   , RS_CANCELED, RM_OS, 26 ) // C920181A
#define OS_INVALID_IPC_ARGUMENT          MAKERESULT(RL_PERMANENT, RS_WRONGARG, RM_OS, 48 ) // D9001830
#define OS_INVALID_IPC_HEADER            MAKERESULT(RL_PERMANENT, RS_WRONGARG, RM_OS, 47 ) // D900182F
#define OS_EXCEEDED_HANDLES_INDEX        MAKERESULT(RL_PERMANENT, RS_WRONGARG, RM_OS, 49 ) // D9001831

// module specific fs

#define FS_UNSUPPORTED_NOT_IMPLEMENTED MAKERESULT(RL_USAGE, RS_NOTSUPPORTED, RM_FS, 760) // E0C046F8

// general am

#define AM_OUT_OF_MEMORY                 MAKERESULT(RL_PERMANENT, RS_OUTOFRESOURCE, RM_AM, RD_OUT_OF_MEMORY     )
#define AM_INTERNAL_RANGE                MAKERESULT(RL_FATAL    , RS_INTERNAL     , RM_AM, RD_OUT_OF_RANGE      )
#define AM_CANCELED_RANGE                MAKERESULT(RL_FATAL    , RS_CANCELED     , RM_AM, RD_OUT_OF_RANGE      )
#define AM_INVALID_SIZE                  MAKERESULT(RL_USAGE    , RS_INVALIDARG   , RM_AM, RD_INVALID_SIZE      )
#define AM_NOT_FOUND                     MAKERESULT(RL_PERMANENT, RS_INVALIDSTATE , RM_AM, RD_NOT_FOUND         )
#define AM_INVALID_ENUM_VALUE            MAKERESULT(RL_PERMANENT, RS_NOTSUPPORTED , RM_AM, RD_INVALID_ENUM_VALUE)
#define AM_NOT_IMPLEMENTED               MAKERESULT(RL_FATAL    , RS_NOTSUPPORTED , RM_AM, RD_NOT_IMPLEMENTED   )

// general os

#define OS_MISALIGNED_ADDRESS            MAKERESULT(RL_USAGE, RS_INVALIDARG, RM_OS, RD_MISALIGNED_ADDRESS)

#endif